# Generated by Django 2.1.1 on 2019-03-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='contacts',
            field=models.CharField(default='test user', max_length=255, unique=True, verbose_name='contacts'),
        ),
    ]
